// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertMultiple(arg1:Array<string>,arg2:string):Promise<void>;

export function ConvertTo(arg1:string,arg2:string):Promise<void>;

export function GetFile():Promise<Array<string>>;

export function PopError(arg1:string,arg2:string):Promise<void>;

export function PopMessage(arg1:string,arg2:string):Promise<void>;
