// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertMultiple(arg1, arg2) {
  return window['go']['conversor']['App']['ConvertMultiple'](arg1, arg2);
}

export function ConvertTo(arg1, arg2) {
  return window['go']['conversor']['App']['ConvertTo'](arg1, arg2);
}

export function GetFile() {
  return window['go']['conversor']['App']['GetFile']();
}

export function PopError(arg1, arg2) {
  return window['go']['conversor']['App']['PopError'](arg1, arg2);
}

export function PopMessage(arg1, arg2) {
  return window['go']['conversor']['App']['PopMessage'](arg1, arg2);
}
